# Generated by Django 5.2.5 on 2025-12-04 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_rolechangerequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoleChangeRequest',
        ),
    ]
