# Generated by Django 5.2.5 on 2025-11-30 09:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='contact_numbers',
            new_name='company1',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='supervisor1',
            new_name='company2',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='email',
            new_name='contact1_email',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='contact_person',
            new_name='contact1_name',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='supervisor2',
            new_name='contact2_name',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='address',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='department',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='name',
        ),
        migrations.AddField(
            model_name='partner',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='contact1_phone',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='contact2_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='contact2_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 30, 17, 57, 47, 597993)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='PartnerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='partners.partner')),
            ],
        ),
        migrations.CreateModel(
            name='PartnershipActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='partners.partner')),
            ],
        ),
    ]
