# Generated by Django 5.2.5 on 2025-12-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_delete_rolechangerequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='college1',
            new_name='college',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='college2',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='company1',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='company2',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='contact1_email',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='contact1_name',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='contact1_phone',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='contact2_email',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='contact2_name',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='contact2_phone',
        ),
        migrations.AddField(
            model_name='partner',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='partnercontact',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
