# Generated by Django 5.2.5 on 2025-11-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_rename_contact_numbers_partner_company1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='category',
        ),
        migrations.AddField(
            model_name='partner',
            name='college1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='college2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='contact1_phone',
            field=models.CharField(default='0000000000', max_length=50),
        ),
    ]
