# Generated by Django 5.2.5 on 2025-12-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_rename_college1_partner_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='partnercontact',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
