# Generated by Django 5.2.5 on 2025-12-05 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_alter_partner_status_alter_partnercontact_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartnershipActivity',
        ),
    ]
