# Generated by Django 5.2.5 on 2025-12-05 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_delete_partnershipactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.college'),
        ),
    ]
