# Generated by Django 5.2.5 on 2025-12-01 08:04

from django.db import migrations


def add_colleges_and_departments(apps, schema_editor):
    College = apps.get_model("partners", "College")
    Department = apps.get_model("partners", "Department")

    # --- Colleges and their Departments ---

    # CET
    cet = College.objects.create(name="CET")
    Department.objects.bulk_create([
        Department(name="BSIT", college=cet),
        Department(name="BLIS", college=cet),
        Department(name="BSECE", college=cet),
        Department(name="BSCE", college=cet),
        Department(name="BSCpe", college=cet),
    ])

    # CHATME
    chatme = College.objects.create(name="CHATME")
    Department.objects.bulk_create([
        Department(name="BSHM", college=chatme),
        Department(name="BSTM", college=chatme),
    ])

    # CCJE
    ccje = College.objects.create(name="CCJE")
    Department.objects.create(name="Criminology", college=ccje)

    # HUSOCOM
    husocom = College.objects.create(name="HUSOCOM")
    Department.objects.bulk_create([
        Department(name="Bachelor of Arts", college=husocom),
        Department(name="Political Science", college=husocom),
        Department(name="Communication Specializing in Journalism and Broadcasting", college=husocom),
        Department(name="Communication Specializing in New Media Studies", college=husocom),
        Department(name="Communication Specializing in Social Communications", college=husocom),
        Department(name="English Language Studies", college=husocom),
        Department(name="History", college=husocom),
        Department(name="Philosophy", college=husocom),
        Department(name="Psychology", college=husocom),
        Department(name="Social Work", college=husocom),
    ])

    # COME
    come = College.objects.create(name="COME")
    Department.objects.create(name="Bachelor of Science in Marine Transportation", college=come)

    # SBME
    sbme = College.objects.create(name="SBME")
    Department.objects.bulk_create([
        Department(name="Bachelor of Science in Accountancy", college=sbme),
        Department(name="Bachelor of Science in Business Administration major in Financial Management", college=sbme),
        Department(name="Bachelor of Science in Business Administration major in Human Resource Management", college=sbme),
        Department(name="Bachelor of Science in Business Administration major in Marketing Management", college=sbme),
        Department(name="Bachelor of Science in Customs Administration", college=sbme),
        Department(name="Bachelor of Science in Management Accounting", college=sbme),
        Department(name="Bachelor of Science in Real Estate Management", college=sbme),
    ])

    # STE
    ste = College.objects.create(name="STE")
    Department.objects.bulk_create([
        Department(name="Bachelor of Early Childhood Education", college=ste),
        Department(name="Bachelor of Elementary Education", college=ste),
        Department(name="Bachelor of Physical Education", college=ste),
        Department(name="Bachelor of Secondary Education major in English", college=ste),
        Department(name="Bachelor of Secondary Education major in Filipino", college=ste),
        Department(name="Bachelor of Secondary Education major in Mathematics", college=ste),
        Department(name="Bachelor of Secondary Education major in Science", college=ste),
        Department(name="Bachelor of Secondary Education major in Social Studies", college=ste),
        Department(name="Bachelor of Secondary Education major in Values Education with Catechetics", college=ste),
        Department(name="Bachelor of Special Needs Education Generalist", college=ste),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_remove_user_college_alter_user_department_and_more'),
    ]

    operations = [
        migrations.RunPython(add_colleges_and_departments),
    ]
