# Generated by Django 5.2.5 on 2025-12-05 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_alter_partner_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.department'),
        ),
    ]
