# Generated by Django 5.2.5 on 2025-12-01 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_auto_20251201_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='College',
            new_name='college',
        ),
    ]
